---
extra_javascript:
  - jquery.min.js
  - jquery.fancybox.min.js
  - zversions.js
extra_css:
  - extra.css
  - jquery.fancybox.min.css
markdown_extensions:
- meta
- admonition
- footnotes
- meta
- attr_list
- codehilite: {guess_lang: true}
- toc: {permalink: true}
- pymdownx.betterem: {smart_enable: all}
- pymdownx.caret
- pymdownx.critic
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist: {custom_checkbox: true}
- pymdownx.tabbed
- pymdownx.tilde
nav:
- Getting Started:
  - Zerynth in 5 minutes: gettingstarted/index.md
  - ZM1 Development Board: gettingstarted/ZM1-DB.md
  # - ZM1 Evaluation Board: gettingstarted/ZM1-EVA.md
  - 4ZeroBox: gettingstarted/4ZeroBox.md
  - Visual Studio Code: gettingstarted/vscode.md
- Hardware:
  - {Hardware Platforms: hardware/index.md}
  - ZM1-DB: hardware/ZM1-Development-Board.md
  - EXP-SER: hardware/EXP-SER.md
  - EXP-RELAY: hardware/EXP-RELAY.md
  - EXP-IO: hardware/EXP-IO.md
  - EXP-PROTO: hardware/EXP-PROTO.md
  - 4ZeroBox: hardware/4ZeroBox.md
  - {Industrial IoT Kit: hardware/I40Kit.md}
  - {Product Innovation Kit: hardware/productInovv.md}
- Zerynth Cloud:
  - Introduction: zCloud/index.md
  - zDeviceManager: zCloud/zdm_intro.md
  - zStorage: zCloud/zstorage_intro.md
  - zDashboard: zCloud/zdashboard_intro.md
  - Connect to zCloud: zCloud/connect.md
  - Over the Air Updates: zCloud/FOTA.md
- Tutorials and Demos:
  - Tutorials:
    - tutorials/index.md
    - tutorials/cli.md
    - Ethernet and Wifi: tutorials/wifi.md
  - Demos:
    - ZM1-DB and Expansion boards:
      - EXP-RELAY Control Lamp: demos/zm1-db/exp-relay-lamp.md
      - EXP-IO Industrial Data Aquisition : demos/zm1-db/exp-io-temperature.md
      - EXP-PROTO Temperature Monitoring App : demos/zm1-db/ex-proto-bme280.md
      - EXP-SER RS485 Interface : demos/zm1-db/exp-ser-rs485.md
    - 4ZeroBox:
      - demos/4zerobox/hello_4zerobox.md
      - demos/4zerobox/industrial_kit.md
    - zCloud:
      - demos/zCloud/jobs_relays.md
      - demos/zCloud/FOTA_fleet.md
      - Integrate Microsoft Azure IoT with Zerynth Cloud: demos/zCloud/azure_integration.md
- Technical Reference:
    - {Introduction: reference/index.md}
    - Zerynth SDK:
      - Zerynth OS: 
        - reference/os/index.md
        - reference/os/basics.md
        - reference/os/seqmap.md
        - reference/os/pinmap.md
        - reference/os/clang.md
        - reference/os/os.md
      - Development Environment: reference/vscode/index.md
      - Boards and Expansions:
        - reference/libs/expansions/index.md
        - reference/bsp/4zerobox_v9.md
        - reference/bsp/zm1_db.md
        - reference/libs/expansions/exp-io.md
        - reference/libs/expansions/exp-relay.md
        - reference/libs/expansions/exp-ser.md
      - Standard Library:
        - reference/libs/stdlib/builtins.md
        - reference/libs/stdlib/threading.md
        - reference/libs/stdlib/struct.md
        - reference/libs/stdlib/gc.md
        - reference/libs/stdlib/timers.md
        - reference/libs/stdlib/watchdog.md
        - Time and Dates:
          - reference/libs/stdlib/time.md
          - reference/libs/stdlib/datetime.md
          - reference/libs/stdlib/suntime.md
        - Data Structures:
          - reference/libs/stdlib/fifo.md
          - reference/libs/stdlib/queue.md
        - Serialization:
          - reference/libs/stdlib/base64.md
          - reference/libs/stdlib/json.md
          - reference/libs/stdlib/cbor.md
        - Filesystem:
          - reference/libs/stdlib/fs.md
        - Peripherals:
          - reference/libs/stdlib/serial.md
          - reference/libs/stdlib/gpio.md
          - reference/libs/stdlib/i2c.md
          - reference/libs/stdlib/spi.md
          - reference/libs/stdlib/adc.md
          - reference/libs/stdlib/pwm.md
          - reference/libs/stdlib/can.md
          - reference/libs/stdlib/mcu.md
      - Networking:
        - reference/libs/networking/index.md
        - reference/libs/networking/net.md
        - reference/libs/networking/wifi.md
        - reference/libs/networking/eth.md
        - reference/libs/networking/socket.md
      - Protocols:
        - reference/libs/protocols/index.md
        - reference/libs/protocols/ntp.md
        - reference/libs/protocols/http.md
        - reference/libs/protocols/mqtt.md
        - reference/libs/protocols/modbus.md
      - Security and Cryptography:
        - reference/libs/crypto/index.md
        - reference/libs/crypto/element.md
      - Filters:
        - reference/libs/filters/iir_filter.md
      - Math:
        - reference/libs/math/math.md
        - reference/libs/math/bignum.md
      - zDeviceManager:
        - reference/libs/zerynth/zdm/index.md
        - reference/libs/zerynth/zdm/examples.md
      - Time Series Log:
        - reference/libs/zerynth/tslog/index.md
      - Sensors:
        - reference/libs/zerynth/zsensors/index.md
      - Components:
          - reference/libs/components/index.md
          - reference/libs/components/bme280/index.md
          - reference/libs/components/bmp180/index.md
          - reference/libs/components/bno055/index.md
          - reference/libs/components/mcp2515/index.md
          - reference/libs/components/iim42652/index.md
      - Command Line Interface:
          - reference/cli/ztc/index.md
          - reference/cli/zdm/index.md
      - FAQ:
          - reference/faq/hardware.md
          - reference/faq/installer.md
          - reference/faq/vscode.md
          - reference/faq/filesystem.md
      - ZSDK Examples:
          - reference/examples/zerynth-os/hello_zerynth.md
          - reference/examples/zerynth-os/multi_serial.md
          - reference/examples/zerynth-os/multi_thread_basic.md
          - reference/examples/zerynth-os/c_language_interface.md
          - reference/examples/zerynth-os/adc.md
          - reference/examples/zerynth-os/watchdog.md
    - zCloud APIs:
      - reference/api/zdm/index.md
      - reference/api/zstorage/index.md
    - zCloud Web App:
      - Zerynth Device Manager : reference/webApp/zdm_gui.md
      - Zerynth Storage: reference/webApp/storage_gui.md
      - Zerynth Dashboard: reference/webApp/Dashboard_gui.md

    - Changelog: reference/changelogs/index.md
    - What's new in Zerynth v3.x: reference/changelogs/whatsnew.md
    - Support plan for 3rd Party devices: reference/device_support.md




plugins:
- search
- minify: {minify_html: true}
site_name: Zerynth Documentation
theme:
    custom_dir: material
    favicon: images/favicon.png
    features:
      - navigation.tabs
    font: {code: Roboto Mono, text: Roboto}
    logo: images/favicon-white.png
    name: material
    palette: {accent: red, primary: indigo}
google_analytics:
  - UA-64288331-2
  - auto
...
